/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java;

import org.junit.Test;
import static org.junit.Assert.*;
import src.main.java.App;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.toString());
    }
}
